trigger:
    - main
    
pool:
 vmImage: 'ubuntu-latest'

variables:
  system.debug: true
  aws.rolecredential.maxduration: "3600" 

steps:
- task: AWSShellScript@1
  continueOnError: true
  displayName: "testing oidc endpoints"
  inputs:
    awsCredentials: 'azure-aws-oidc'
    regionName: 'us-east-2'
    scriptType: inline
    inlineScript: |
      aws sts get-caller-identity
      aws ecr list-images --repository-name 881986476278.dkr.ecr.us-east-2.amazonaws.com/nn
